import asyncio

content= """
        # Demo README

        This is a sample README file created by an automated MAF agent.

        ## Purpose
        This repository is used for testing automated GitHub operations.

        ## Notes
        - This is dummy content
        - Created for testing purposes"""

from agents.CO_ORDINATOR_AGENT.co_ordinator_agent import CoOrdinatorAgent
from agents.GITHUB_AGENT.github_agent import GithubAgent
import asyncio
from utils.prompt_manager_v2 import TestUserPrompt






title="Terraform workflow validation failing for Azure deployment",
body="""
## Issue Description
The generated Terraform GitHub Actions workflow is failing during the validation stage for Azure infrastructure deployment.

## Observed Error
terraform validate returned an error indicating invalid provider configuration.

## Expected Behavior
The workflow should:
- Initialize Terraform successfully
- Validate configuration
- Generate terraform plan
- Deploy Azure resources

## Steps to Reproduce
1. Trigger GitHub Actions workflow
2. Observe Terraform Validate step
3. Validation fails before terraform plan

## Possible Root Cause
- Missing Azure provider configuration
- Invalid backend configuration
- Missing environment variables
- Incorrect working-directory

## Suggested Fix
- Verify provider.tf configuration
- Validate ARM_* environment variables
- Ensure backend block exists
- Add terraform fmt validation

## Additional Context
Workflow generated by yaml_agent and validated through validation_agent.
"""



async def main():
    coordinator = CoOrdinatorAgent.get_instance()
    # response= await coordinator.run(f" Please create an issue for the below repository and these are the details :\n Repo Name: RAGHAVENDRA-VAM/Workflow-files\n Branch : main \n title : {title} \n details :{body}")
    response = await coordinator.run(str(TestUserPrompt("CI_builder_test_prompt"))) #type: ignore
    print(response)

asyncio.run(main())

